openapi: 3.0.1
info:
  title: Operator API
  version: 1.0.0
servers:
  - url: http://localhost
    description: My server

paths:
  /op/add:
    post:
      summary: Add a new operator
      operationId: AddOp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operator'
      responses:
        '200':
          description: Operator added successfully
        '400':
          description: Invalid input
  /company/operator:
    get:
      summary: Get all operators
      operationId: listOp
      responses:
        '200':
          description: List of all operators
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Operator'
  /op/{id}:
    get:
      summary: Get operator by ID
      operationId: getOp
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operator found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Operator' 

  /op/update/{id}:
    put:
      summary: Update operator availability
      operationId: updateOpAvailability
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                isavaible:
                  type: boolean
      responses:
        '204':
          description: Operator updated
        '400':
          description: Invalid input
  /op/delete/{id}:
    delete:
      summary: Delete operator by ID
      operationId: deleteOp
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '204':
          description: Operator deleted
        '404':
          description: Operator not found
components:
  schemas:
    Operator:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minLength: 6
          maxLength: 6
        nameop:
          type: string
        surnameop:
          type: string
        numReq:
          type: integer
          format: int32
        isavaible:
          type: boolean
      required:
        - id
        - nameop
        - surnameop
        - numReq
        - isavaible
